package battle

type (
	Move struct {
		Name     string
		Type     PokemonType
		Category DamageCategory
		PP       uint8
		Power    int
		Accuracy int
		Effect   func(board *Board, target *BoardPosition)
	}

	DamageCategory uint8
	MoveEffect     uint8
)

const (
	CATEGORY_NONE = iota
	CATEGORY_PHYSICAL
	CATEGORY_SPECIAL
	CATEGORY_STATUS
)

var (
	Moves = [166]Move{
		{Name: "", Type: TYPE_NONE, Category: CATEGORY_NONE, PP: 0, Power: 0, Accuracy: 0},
		{Name: "Pound", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 35, Power: 40, Accuracy: 100},
		{Name: "Karate Chop", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 25, Power: 50, Accuracy: 100},
		{Name: "Double Slap", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 10, Power: 15, Accuracy: 85},
		{Name: "Comet Punch", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 15, Power: 18, Accuracy: 85},
		{Name: "Mega Punch", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 80, Accuracy: 85},
		{Name: "Pay Day", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 40, Accuracy: 100},
		{Name: "Fire Punch", Type: TYPE_FIRE, Category: CATEGORY_PHYSICAL, PP: 15, Power: 75, Accuracy: 100, Effect: func(b *Board, t *BoardPosition) { MoveEffectStatus(b, t, STATUS_BURNED, 10) }},
		{Name: "Ice Punch", Type: TYPE_ICE, Category: CATEGORY_PHYSICAL, PP: 15, Power: 75, Accuracy: 100, Effect: func(b *Board, t *BoardPosition) { MoveEffectStatus(b, t, STATUS_FROZEN, 10) }},
		{Name: "Thunder Punch", Type: TYPE_ELECTRIC, Category: CATEGORY_PHYSICAL, PP: 15, Power: 75, Accuracy: 100, Effect: func(b *Board, t *BoardPosition) { MoveEffectStatus(b, t, STATUS_PARALYZED, 10) }},
		{Name: "Scratch", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 35, Power: 40, Accuracy: 100},
		{Name: "Vise Grip", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 30, Power: 55, Accuracy: 100},
		{Name: "Guillotine", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 5, Power: -1, Accuracy: 30},
		{Name: "Razor Wind", Type: TYPE_NORMAL, Category: CATEGORY_SPECIAL, PP: 10, Power: 80, Accuracy: 75},
		{Name: "Swords Dance", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Cut", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 30, Power: 50, Accuracy: 95},
		{Name: "Gust", Type: TYPE_NORMAL, Category: CATEGORY_SPECIAL, PP: 35, Power: 40, Accuracy: 100},
		{Name: "Wing Attack", Type: TYPE_FLYING, Category: CATEGORY_PHYSICAL, PP: 35, Power: 35, Accuracy: 100},
		{Name: "Whirlwind", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: 85},
		{Name: "Fly", Type: TYPE_FLYING, Category: CATEGORY_PHYSICAL, PP: 15, Power: 70, Accuracy: 95},
		{Name: "Bind", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 15, Accuracy: 75},
		{Name: "Slam", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 80, Accuracy: 75},
		{Name: "Vine Whip", Type: TYPE_GRASS, Category: CATEGORY_PHYSICAL, PP: 10, Power: 35, Accuracy: 100},
		{Name: "Stomp", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 65, Accuracy: 100},
		{Name: "Double Kick", Type: TYPE_FIGHTING, Category: CATEGORY_PHYSICAL, PP: 30, Power: 30, Accuracy: 100},
		{Name: "Mega Kick", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 5, Power: 120, Accuracy: 75},
		{Name: "Jump Kick", Type: TYPE_FIGHTING, Category: CATEGORY_PHYSICAL, PP: 25, Power: 70, Accuracy: 95},
		{Name: "Rolling Kick", Type: TYPE_FIGHTING, Category: CATEGORY_PHYSICAL, PP: 15, Power: 60, Accuracy: 85},
		{Name: "Sand Attack", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 15, Power: -1, Accuracy: 100},
		{Name: "Headbutt", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 15, Power: 70, Accuracy: 100},
		{Name: "Horn Attack", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 25, Power: 65, Accuracy: 100},
		{Name: "Fury Attack", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 15, Accuracy: 85},
		{Name: "Horn Drill", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 5, Power: -1, Accuracy: 30},
		{Name: "Tackle", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 35, Power: 35, Accuracy: 95},
		{Name: "Body Slam", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 15, Power: 85, Accuracy: 100},
		{Name: "Wrap", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 15, Accuracy: 85},
		{Name: "Take Down", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 90, Accuracy: 85},
		{Name: "Thrash", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 90, Accuracy: 100},
		{Name: "Double-Edge", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 15, Power: 100, Accuracy: 100},
		{Name: "Tail Whip", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: 100},
		{Name: "Poison Sting", Type: TYPE_POISON, Category: CATEGORY_PHYSICAL, PP: 35, Power: 15, Accuracy: 100},
		{Name: "Twineedle", Type: TYPE_BUG, Category: CATEGORY_PHYSICAL, PP: 20, Power: 25, Accuracy: 100},
		{Name: "Pin Missile", Type: TYPE_BUG, Category: CATEGORY_PHYSICAL, PP: 20, Power: 14, Accuracy: 85},
		{Name: "Leer", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: 100},
		{Name: "Bite", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 25, Power: 60, Accuracy: 100},
		{Name: "Growl", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: 100},
		{Name: "Roar", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: 100},
		{Name: "Sing", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 15, Power: -1, Accuracy: 55},
		{Name: "Supersonic", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: 55},
		{Name: "Sonic Boom", Type: TYPE_NORMAL, Category: CATEGORY_SPECIAL, PP: 20, Power: -1, Accuracy: 90},
		{Name: "Disable", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: 55},
		{Name: "Acid", Type: TYPE_POISON, Category: CATEGORY_SPECIAL, PP: 30, Power: 40, Accuracy: 100},
		{Name: "Ember", Type: TYPE_FIRE, Category: CATEGORY_SPECIAL, PP: 25, Power: 40, Accuracy: 100},
		{Name: "Flamethrower", Type: TYPE_FIRE, Category: CATEGORY_SPECIAL, PP: 15, Power: 95, Accuracy: 100},
		{Name: "Mist", Type: TYPE_ICE, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Water Gun", Type: TYPE_WATER, Category: CATEGORY_SPECIAL, PP: 25, Power: 40, Accuracy: 100},
		{Name: "Hydro Pump", Type: TYPE_WATER, Category: CATEGORY_SPECIAL, PP: 5, Power: 120, Accuracy: 80},
		{Name: "Surf", Type: TYPE_WATER, Category: CATEGORY_SPECIAL, PP: 15, Power: 95, Accuracy: 100},
		{Name: "Ice Beam", Type: TYPE_ICE, Category: CATEGORY_SPECIAL, PP: 10, Power: 95, Accuracy: 100},
		{Name: "Blizzard", Type: TYPE_ICE, Category: CATEGORY_SPECIAL, PP: 5, Power: 120, Accuracy: 90},
		{Name: "Psybeam", Type: TYPE_PSYCHIC, Category: CATEGORY_SPECIAL, PP: 20, Power: 65, Accuracy: 100},
		{Name: "Bubble Beam", Type: TYPE_WATER, Category: CATEGORY_SPECIAL, PP: 20, Power: 65, Accuracy: 100},
		{Name: "Aurora Beam", Type: TYPE_ICE, Category: CATEGORY_SPECIAL, PP: 20, Power: 65, Accuracy: 100},
		{Name: "Hyper Beam", Type: TYPE_NORMAL, Category: CATEGORY_SPECIAL, PP: 5, Power: 150, Accuracy: 90},
		{Name: "Peck", Type: TYPE_FLYING, Category: CATEGORY_PHYSICAL, PP: 35, Power: 35, Accuracy: 100},
		{Name: "Drill Peck", Type: TYPE_FLYING, Category: CATEGORY_PHYSICAL, PP: 20, Power: 80, Accuracy: 100},
		{Name: "Submission", Type: TYPE_FIGHTING, Category: CATEGORY_PHYSICAL, PP: 25, Power: 80, Accuracy: 80},
		{Name: "Low Kick", Type: TYPE_FIGHTING, Category: CATEGORY_PHYSICAL, PP: 20, Power: 50, Accuracy: 90},
		{Name: "Counter", Type: TYPE_FIGHTING, Category: CATEGORY_PHYSICAL, PP: 20, Power: -1, Accuracy: 100},
		{Name: "Seismic Toss", Type: TYPE_FIGHTING, Category: CATEGORY_PHYSICAL, PP: 20, Power: -1, Accuracy: 100},
		{Name: "Strength", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 15, Power: 80, Accuracy: 100},
		{Name: "Absorb", Type: TYPE_GRASS, Category: CATEGORY_SPECIAL, PP: 20, Power: 20, Accuracy: 100},
		{Name: "Mega Drain", Type: TYPE_GRASS, Category: CATEGORY_SPECIAL, PP: 10, Power: 40, Accuracy: 100},
		{Name: "Leech Seed", Type: TYPE_GRASS, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: 90},
		{Name: "Growth", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: -1},
		{Name: "Razor Leaf", Type: TYPE_GRASS, Category: CATEGORY_PHYSICAL, PP: 25, Power: 55, Accuracy: 95},
		{Name: "Solar Beam", Type: TYPE_GRASS, Category: CATEGORY_SPECIAL, PP: 10, Power: 120, Accuracy: 100},
		{Name: "Poison Powder", Type: TYPE_POISON, Category: CATEGORY_STATUS, PP: 35, Power: -1, Accuracy: 75},
		{Name: "Stun Spore", Type: TYPE_GRASS, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: 75},
		{Name: "Sleep Powder", Type: TYPE_GRASS, Category: CATEGORY_STATUS, PP: 15, Power: -1, Accuracy: 75},
		{Name: "Petal Dance", Type: TYPE_GRASS, Category: CATEGORY_SPECIAL, PP: 20, Power: 70, Accuracy: 100},
		{Name: "String Shot", Type: TYPE_BUG, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: 95},
		{Name: "Dragon Rage", Type: TYPE_DRAGON, Category: CATEGORY_SPECIAL, PP: 10, Power: -1, Accuracy: 100},
		{Name: "Fire Spin", Type: TYPE_FIRE, Category: CATEGORY_SPECIAL, PP: 15, Power: 15, Accuracy: 70},
		{Name: "Thunder Shock", Type: TYPE_ELECTRIC, Category: CATEGORY_SPECIAL, PP: 30, Power: 40, Accuracy: 100},
		{Name: "Thunderbolt", Type: TYPE_ELECTRIC, Category: CATEGORY_SPECIAL, PP: 15, Power: 95, Accuracy: 100},
		{Name: "Thunder Wave", Type: TYPE_ELECTRIC, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: 100},
		{Name: "Thunder", Type: TYPE_ELECTRIC, Category: CATEGORY_SPECIAL, PP: 10, Power: 120, Accuracy: 70},
		{Name: "Rock Throw", Type: TYPE_ROCK, Category: CATEGORY_PHYSICAL, PP: 15, Power: 50, Accuracy: 65},
		{Name: "Earthquake", Type: TYPE_GROUND, Category: CATEGORY_PHYSICAL, PP: 10, Power: 100, Accuracy: 100},
		{Name: "Fissure", Type: TYPE_GROUND, Category: CATEGORY_PHYSICAL, PP: 5, Power: -1, Accuracy: 30},
		{Name: "Dig", Type: TYPE_GROUND, Category: CATEGORY_PHYSICAL, PP: 10, Power: 100, Accuracy: 100},
		{Name: "Toxic", Type: TYPE_POISON, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: 85},
		{Name: "Confusion", Type: TYPE_PSYCHIC, Category: CATEGORY_SPECIAL, PP: 25, Power: 50, Accuracy: 100},
		{Name: "Psychic", Type: TYPE_PSYCHIC, Category: CATEGORY_SPECIAL, PP: 10, Power: 90, Accuracy: 100},
		{Name: "Hypnosis", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: 60},
		{Name: "Meditate", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: -1},
		{Name: "Agility", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Quick Attack", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 30, Power: 40, Accuracy: 100},
		{Name: "Rage", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 20, Accuracy: 100},
		{Name: "Teleport", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: -1},
		{Name: "Night Shade", Type: TYPE_GHOST, Category: CATEGORY_SPECIAL, PP: 15, Power: -1, Accuracy: 100},
		{Name: "Mimic", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: 100},
		{Name: "Screech", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: 85},
		{Name: "Double Team", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 15, Power: -1, Accuracy: -1},
		{Name: "Recover", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: -1},
		{Name: "Harden", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Minimize", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: -1},
		{Name: "Smokescreen", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: 100},
		{Name: "Confuse Ray", Type: TYPE_GHOST, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: 100},
		{Name: "Withdraw", Type: TYPE_WATER, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: -1},
		{Name: "Defense Curl", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: -1},
		{Name: "Barrier", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Light Screen", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Haze", Type: TYPE_ICE, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Reflect", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: -1},
		{Name: "Focus Energy", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Bide", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 10, Power: -1, Accuracy: 100},
		{Name: "Metronome", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: -1},
		{Name: "Mirror Move", Type: TYPE_FLYING, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: -1},
		{Name: "Self-Destruct", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 5, Power: 130, Accuracy: 100},
		{Name: "Egg Bomb", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 10, Power: 100, Accuracy: 75},
		{Name: "Lick", Type: TYPE_GHOST, Category: CATEGORY_PHYSICAL, PP: 30, Power: 20, Accuracy: 100},
		{Name: "Smog", Type: TYPE_POISON, Category: CATEGORY_SPECIAL, PP: 20, Power: 20, Accuracy: 70},
		{Name: "Sludge", Type: TYPE_POISON, Category: CATEGORY_SPECIAL, PP: 20, Power: 65, Accuracy: 100},
		{Name: "Bone Club", Type: TYPE_GROUND, Category: CATEGORY_PHYSICAL, PP: 20, Power: 65, Accuracy: 85},
		{Name: "Fire Blast", Type: TYPE_FIRE, Category: CATEGORY_SPECIAL, PP: 5, Power: 120, Accuracy: 85},
		{Name: "Waterfall", Type: TYPE_WATER, Category: CATEGORY_PHYSICAL, PP: 15, Power: 80, Accuracy: 100},
		{Name: "Clamp", Type: TYPE_WATER, Category: CATEGORY_PHYSICAL, PP: 10, Power: 35, Accuracy: 75},
		{Name: "Swift", Type: TYPE_NORMAL, Category: CATEGORY_SPECIAL, PP: 20, Power: 60, Accuracy: -1},
		{Name: "Skull Bash", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 15, Power: 100, Accuracy: 100},
		{Name: "Spike Cannon", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 15, Power: 20, Accuracy: 100},
		{Name: "Constrict", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 35, Power: 10, Accuracy: 100},
		{Name: "Amnesia", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: -1},
		{Name: "Kinesis", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 15, Power: -1, Accuracy: 80},
		{Name: "Soft-Boiled", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: -1},
		{Name: "High Jump Kick", Type: TYPE_FIGHTING, Category: CATEGORY_PHYSICAL, PP: 20, Power: 85, Accuracy: 90},
		{Name: "Glare", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: 75},
		{Name: "Dream Eater", Type: TYPE_PSYCHIC, Category: CATEGORY_SPECIAL, PP: 15, Power: 100, Accuracy: 100},
		{Name: "Poison Gas", Type: TYPE_POISON, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: 55},
		{Name: "Barrage", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 15, Accuracy: 85},
		{Name: "Leech Life", Type: TYPE_BUG, Category: CATEGORY_PHYSICAL, PP: 15, Power: 20, Accuracy: 100},
		{Name: "Lovely Kiss", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: 75},
		{Name: "Sky Attack", Type: TYPE_FLYING, Category: CATEGORY_PHYSICAL, PP: 5, Power: 140, Accuracy: 90},
		{Name: "Transform", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: -1},
		{Name: "Bubble", Type: TYPE_WATER, Category: CATEGORY_SPECIAL, PP: 30, Power: 20, Accuracy: 100},
		{Name: "Dizzy Punch", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 10, Power: 70, Accuracy: 100},
		{Name: "Spore", Type: TYPE_GRASS, Category: CATEGORY_STATUS, PP: 15, Power: -1, Accuracy: 100},
		{Name: "Flash", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 20, Power: -1, Accuracy: 70},
		{Name: "Psywave", Type: TYPE_PSYCHIC, Category: CATEGORY_SPECIAL, PP: 15, Power: -1, Accuracy: 80},
		{Name: "Splash", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: -1},
		{Name: "Acid Armor", Type: TYPE_POISON, Category: CATEGORY_STATUS, PP: 40, Power: -1, Accuracy: -1},
		{Name: "Crabhammer", Type: TYPE_WATER, Category: CATEGORY_PHYSICAL, PP: 10, Power: 90, Accuracy: 85},
		{Name: "Explosion", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 5, Power: 170, Accuracy: 100},
		{Name: "Fury Swipes", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 15, Power: 18, Accuracy: 80},
		{Name: "Bonemerang", Type: TYPE_GROUND, Category: CATEGORY_PHYSICAL, PP: 10, Power: 50, Accuracy: 90},
		{Name: "Rest", Type: TYPE_PSYCHIC, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: -1},
		{Name: "Rock Slide", Type: TYPE_ROCK, Category: CATEGORY_PHYSICAL, PP: 10, Power: 75, Accuracy: 90},
		{Name: "Hyper Fang", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 15, Power: 80, Accuracy: 90},
		{Name: "Sharpen", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Conversion", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 30, Power: -1, Accuracy: -1},
		{Name: "Tri Attack", Type: TYPE_NORMAL, Category: CATEGORY_SPECIAL, PP: 10, Power: 80, Accuracy: 100},
		{Name: "Super Fang", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 10, Power: -1, Accuracy: 90},
		{Name: "Slash", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 20, Power: 70, Accuracy: 100},
		{Name: "Substitute", Type: TYPE_NORMAL, Category: CATEGORY_STATUS, PP: 10, Power: -1, Accuracy: -1},
		{Name: "Struggle", Type: TYPE_NORMAL, Category: CATEGORY_PHYSICAL, PP: 10, Power: 50, Accuracy: 100},
	}
)
